import type { OrgProfile, NormalizedOpportunity } from "./types";

// ─── Mock Organizations ───────────────────────────────────────────────────────

export const MOCK_ORGANIZATIONS: OrgProfile[] = [
  {
    id: "org_001",
    name: "Empower Birth Initiative",
    org_type: "nonprofit",
    mission: "Improve maternal health outcomes for Black women through education, advocacy, and community-based support.",
    program_areas: ["maternal health", "health equity", "community education"],
    population_served: ["Black women", "pregnant people", "families"],
    geography: ["Ohio", "United States"],
    annual_budget: 350000,
    years_in_operation: 3,
    has_501c3: true,
    is_small_business: false,
    keywords: ["maternal health", "birth equity", "pregnancy", "community health", "advocacy"],
  },
  {
    id: "org_002",
    name: "GreenWorks Youth Lab",
    org_type: "nonprofit",
    mission: "Prepare youth for climate and clean energy careers through workforce training and STEM programs.",
    program_areas: ["workforce development", "climate", "STEM education", "youth training"],
    population_served: ["youth", "students", "underserved communities"],
    geography: ["California", "United States"],
    annual_budget: 1200000,
    years_in_operation: 7,
    has_501c3: true,
    is_small_business: false,
    keywords: ["climate", "clean energy", "workforce", "youth development", "STEM"],
  },
  {
    id: "org_003",
    name: "CivicData Solutions",
    org_type: "small_business",
    mission: "Build data tools that help public agencies improve service delivery and operational efficiency.",
    program_areas: ["govtech", "data systems", "public sector innovation"],
    population_served: ["public agencies", "local governments"],
    geography: ["United States"],
    annual_budget: 900000,
    years_in_operation: 2,
    has_501c3: false,
    is_small_business: true,
    keywords: ["SaaS", "data analytics", "government technology", "procurement", "civic tech"],
  },
];

// ─── Mock Opportunities: Active Sources (20) ─────────────────────────────────

export const MOCK_OPPORTUNITIES_ACTIVE: NormalizedOpportunity[] = [
  // ── Simpler Grants (3) ───────────────────────────────────────────────────
  {
    id: "sg_001",
    source: "simpler_grants",
    source_raw: "Simpler Grants",
    title: "Maternal and Child Health Equity Initiative FY2026",
    description: "Supports community-based organizations addressing racial and ethnic disparities in maternal health outcomes. Priority given to organizations serving Black and Indigenous communities.",
    agency: "Health Resources & Services Administration (HRSA)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-01",
    close_date: "2026-05-30",
    min_award: 100000,
    max_award: 500000,
    eligibility: ["nonprofit", "501c3", "community_based_org"],
    categories: ["maternal health", "health equity", "community health"],
    keywords: ["maternal mortality", "birth equity", "Black women", "community health", "health disparities"],
    geography: ["United States"],
    url: "https://simpler.grants.gov/opportunities/sg_001",
  },
  {
    id: "sg_002",
    source: "simpler_grants",
    source_raw: "Simpler Grants",
    title: "Climate Workforce Development Grant – Clean Energy Transitions",
    description: "Funds organizations training workers for clean energy sector jobs. Focuses on youth in underserved communities, STEM skills, and green economy career readiness.",
    agency: "Department of Energy (DOE)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-01-15",
    close_date: "2026-04-15",
    min_award: 500000,
    max_award: 2000000,
    eligibility: ["nonprofit", "501c3", "educational_institution"],
    categories: ["workforce development", "climate", "STEM", "clean energy"],
    keywords: ["clean energy", "workforce", "youth", "STEM", "climate jobs", "underserved"],
    geography: ["United States"],
    url: "https://simpler.grants.gov/opportunities/sg_002",
  },
  {
    id: "sg_003",
    source: "simpler_grants",
    source_raw: "Simpler Grants",
    title: "Environmental Justice Community Action Program",
    description: "Empowers underserved communities most impacted by environmental hazards and climate change to develop solutions and advocate for protective policies.",
    agency: "Environmental Protection Agency (EPA)",
    funding_type: "cooperative_agreement",
    status: "active",
    open_date: "2026-03-01",
    close_date: "2026-06-01",
    min_award: 200000,
    max_award: 800000,
    eligibility: ["nonprofit", "501c3", "tribal_organization"],
    categories: ["environmental justice", "community advocacy", "climate"],
    keywords: ["environmental justice", "climate", "community", "equity", "pollution"],
    geography: ["United States"],
    url: "https://simpler.grants.gov/opportunities/sg_003",
  },

  // ── Grants.gov (3) ───────────────────────────────────────────────────────
  {
    id: "gg_001",
    source: "grants_gov",
    source_raw: "Grants.gov",
    title: "Community Health Worker Training and Deployment Grant",
    description: "Supports training and deployment of community health workers to reduce health disparities in underserved areas. Priority for maternal and infant health, chronic disease.",
    agency: "Centers for Disease Control and Prevention (CDC)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-01-20",
    close_date: "2026-04-20",
    min_award: 150000,
    max_award: 600000,
    eligibility: ["nonprofit", "501c3", "public_health_agency"],
    categories: ["community health", "workforce", "health equity", "maternal health"],
    keywords: ["community health worker", "health disparities", "maternal health", "training", "underserved"],
    geography: ["United States"],
    url: "https://grants.gov/search-results-detail/gg_001",
  },
  {
    id: "gg_002",
    source: "grants_gov",
    source_raw: "Grants.gov",
    title: "STEM Education and Workforce Development for Underrepresented Youth",
    description: "Funds programs expanding access to quality STEM education and career pathways for underrepresented youth, including climate and clean energy curriculum.",
    agency: "National Science Foundation (NSF)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-10",
    close_date: "2026-05-10",
    min_award: 300000,
    max_award: 1500000,
    eligibility: ["nonprofit", "501c3", "educational_institution"],
    categories: ["STEM", "education", "youth", "workforce"],
    keywords: ["STEM", "youth", "education", "underrepresented", "workforce", "climate"],
    geography: ["United States"],
    url: "https://grants.gov/search-results-detail/gg_002",
  },
  {
    id: "gg_003",
    source: "grants_gov",
    source_raw: "Grants.gov",
    title: "Digital Government Services Modernization Grant",
    description: "Supports state and local governments in modernizing digital service delivery using data analytics and human-centered design. Open to government contractors and tech vendors.",
    agency: "General Services Administration (GSA)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-03-05",
    close_date: "2026-06-05",
    min_award: 250000,
    max_award: 1000000,
    eligibility: ["small_business", "nonprofit", "government", "for_profit"],
    categories: ["government technology", "digital services", "data"],
    keywords: ["govtech", "digital government", "data analytics", "public sector", "modernization"],
    geography: ["United States"],
    url: "https://grants.gov/search-results-detail/gg_003",
  },

  // ── SAM.gov (3) ──────────────────────────────────────────────────────────
  {
    id: "sam_001",
    source: "sam_gov",
    source_raw: "SAM.gov",
    title: "Data Analytics and Visualization Platform – Federal Agency RFP",
    description: "Federal agency seeking contractor to build and maintain a data analytics and visualization platform for operational reporting and service delivery improvement.",
    agency: "Department of Health and Human Services (HHS)",
    funding_type: "contract",
    status: "active",
    open_date: "2026-02-15",
    close_date: "2026-04-30",
    min_award: 500000,
    max_award: 3000000,
    eligibility: ["small_business", "for_profit", "8a_certified"],
    categories: ["data analytics", "technology", "procurement"],
    keywords: ["data analytics", "visualization", "SaaS", "government", "platform", "reporting"],
    geography: ["United States"],
    url: "https://sam.gov/opp/sam_001/view",
  },
  {
    id: "sam_002",
    source: "sam_gov",
    source_raw: "SAM.gov",
    title: "Civic Technology Innovation – Small Business Set-Aside",
    description: "Procurement opportunity for small businesses offering innovative civic technology solutions to improve local government service delivery, citizen engagement, and operational efficiency.",
    agency: "Office of Management and Budget (OMB)",
    funding_type: "contract",
    status: "active",
    open_date: "2026-03-01",
    close_date: "2026-05-15",
    min_award: 200000,
    max_award: 1500000,
    eligibility: ["small_business"],
    categories: ["govtech", "civic tech", "procurement", "innovation"],
    keywords: ["civic tech", "government technology", "procurement", "small business", "SaaS", "innovation"],
    geography: ["United States"],
    url: "https://sam.gov/opp/sam_002/view",
  },
  {
    id: "sam_003",
    source: "sam_gov",
    source_raw: "SAM.gov",
    title: "Public Health Surveillance and Data Systems Contract",
    description: "Multi-year contract for development and operation of public health data surveillance systems, including maternal and child health tracking components.",
    agency: "Centers for Disease Control and Prevention (CDC)",
    funding_type: "contract",
    status: "active",
    open_date: "2026-01-10",
    close_date: "2026-04-10",
    min_award: 1000000,
    max_award: 5000000,
    eligibility: ["small_business", "for_profit", "nonprofit"],
    categories: ["public health", "data systems", "surveillance"],
    keywords: ["public health", "data systems", "maternal health", "surveillance", "technology"],
    geography: ["United States"],
    url: "https://sam.gov/opp/sam_003/view",
  },

  // ── SBIR (3) ─────────────────────────────────────────────────────────────
  {
    id: "sbir_001",
    source: "sbir",
    source_raw: "SBIR/STTR",
    title: "AI-Powered Maternal Health Risk Assessment Tool – Phase II SBIR",
    description: "NIH SBIR Phase II award for small businesses developing AI/ML tools to predict and prevent adverse maternal health outcomes, with focus on reducing racial disparities.",
    agency: "National Institutes of Health (NIH)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-01",
    close_date: "2026-05-01",
    min_award: 750000,
    max_award: 1500000,
    eligibility: ["small_business", "for_profit"],
    categories: ["health technology", "AI/ML", "maternal health", "research"],
    keywords: ["AI", "maternal health", "risk assessment", "small business", "health technology"],
    geography: ["United States"],
    url: "https://www.sbir.gov/solicitation/sbir_001",
  },
  {
    id: "sbir_002",
    source: "sbir",
    source_raw: "SBIR/STTR",
    title: "Clean Energy Grid Optimization Technology – DOE SBIR Phase I",
    description: "DOE SBIR solicitation for small businesses developing novel clean energy grid technologies, including storage, distributed generation, and demand response systems.",
    agency: "Department of Energy (DOE)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-01-20",
    close_date: "2026-04-20",
    min_award: 150000,
    max_award: 300000,
    eligibility: ["small_business", "for_profit"],
    categories: ["clean energy", "technology", "research", "innovation"],
    keywords: ["clean energy", "grid", "technology", "SBIR", "small business", "innovation"],
    geography: ["United States"],
    url: "https://www.sbir.gov/solicitation/sbir_002",
  },
  {
    id: "sbir_003",
    source: "sbir",
    source_raw: "SBIR/STTR",
    title: "Government Data Interoperability and Analytics Platform – NSF STTR",
    description: "NSF STTR solicitation for small businesses partnering with research institutions to develop data interoperability solutions for federal and state government data systems.",
    agency: "National Science Foundation (NSF)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-15",
    close_date: "2026-05-15",
    min_award: 200000,
    max_award: 500000,
    eligibility: ["small_business", "for_profit"],
    categories: ["data systems", "government technology", "research"],
    keywords: ["data analytics", "government", "interoperability", "SaaS", "civic tech"],
    geography: ["United States"],
    url: "https://www.sbir.gov/solicitation/sbir_003",
  },

  // ── 360Giving / UKRI (2) ─────────────────────────────────────────────────
  {
    id: "ukri_001",
    source: "threesixtygiving",
    source_raw: "360Giving / UKRI",
    title: "Youth Climate Action Research Partnership",
    description: "UKRI funding for collaborative research projects engaging young people in climate action, workforce readiness, and STEM skill development for the green economy.",
    agency: "UK Research and Innovation (UKRI)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-01",
    close_date: "2026-05-01",
    min_award: 100000,
    max_award: 400000,
    eligibility: ["nonprofit", "educational_institution", "research_org"],
    categories: ["climate", "youth", "research", "STEM"],
    keywords: ["youth", "climate", "STEM", "workforce", "research", "UK"],
    geography: ["United Kingdom", "International"],
    url: "https://gtr.ukri.org/projects/ukri_001",
  },
  {
    id: "ukri_002",
    source: "threesixtygiving",
    source_raw: "360Giving / UKRI",
    title: "Community Health Innovation Fund",
    description: "Supports innovative community-led health projects addressing health inequalities and improving outcomes for underserved populations including maternal and child health.",
    agency: "National Institute for Health Research (NIHR)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-03-01",
    close_date: "2026-06-15",
    min_award: 50000,
    max_award: 250000,
    eligibility: ["nonprofit", "community_org"],
    categories: ["community health", "health equity", "innovation"],
    keywords: ["community health", "health equity", "maternal health", "innovation", "UK"],
    geography: ["United Kingdom"],
    url: "https://gtr.ukri.org/projects/ukri_002",
  },

  // ── California Grants (2) ─────────────────────────────────────────────────
  {
    id: "ca_001",
    source: "california_grants",
    source_raw: "California Grants Portal",
    title: "California Climate Investment – Youth Workforce Green Jobs",
    description: "Funds California nonprofits providing green job training and placement services for low-income youth, especially in disadvantaged communities. Part of California Climate Investments.",
    agency: "California Air Resources Board (CARB)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-01-15",
    close_date: "2026-04-15",
    min_award: 200000,
    max_award: 1000000,
    eligibility: ["nonprofit", "501c3"],
    categories: ["workforce development", "climate", "youth", "environmental justice"],
    keywords: ["climate", "workforce", "youth", "California", "green jobs", "disadvantaged"],
    geography: ["California", "United States"],
    url: "https://www.grants.ca.gov/grants/ca_001",
  },
  {
    id: "ca_002",
    source: "california_grants",
    source_raw: "California Grants Portal",
    title: "Maternal and Child Health Equity Grant – California MCH Program",
    description: "California Department of Public Health grant targeting racial disparities in maternal and infant mortality. Priority for community organizations in high-need counties.",
    agency: "California Department of Public Health (CDPH)",
    funding_type: "grant",
    status: "active",
    open_date: "2026-02-20",
    close_date: "2026-05-20",
    min_award: 100000,
    max_award: 400000,
    eligibility: ["nonprofit", "501c3", "community_based_org"],
    categories: ["maternal health", "health equity", "community health"],
    keywords: ["maternal health", "health equity", "California", "Black women", "community health"],
    geography: ["California", "United States"],
    url: "https://www.grants.ca.gov/grants/ca_002",
  },

  // ── World Bank (2) ────────────────────────────────────────────────────────
  {
    id: "wb_001",
    source: "world_bank",
    source_raw: "World Bank",
    title: "Digital Government Transformation – Public Sector ICT Procurement",
    description: "World Bank-funded procurement for digital government transformation services, including data analytics platforms, citizen service portals, and government ICT infrastructure.",
    agency: "World Bank Group – IFC",
    funding_type: "procurement",
    status: "active",
    open_date: "2026-02-01",
    close_date: "2026-05-01",
    min_award: 500000,
    max_award: 5000000,
    eligibility: ["small_business", "for_profit", "nonprofit"],
    categories: ["government technology", "digital services", "procurement", "ICT"],
    keywords: ["government technology", "data analytics", "digital services", "procurement", "ICT"],
    geography: ["International", "Global"],
    url: "https://projects.worldbank.org/wb_001",
  },
  {
    id: "wb_002",
    source: "world_bank",
    source_raw: "World Bank",
    title: "Climate Resilience and Green Energy Infrastructure – Developing Nations",
    description: "Competitive procurement for climate resilience planning, green energy implementation, and environmental advisory services in developing nations.",
    agency: "World Bank Group – IBRD",
    funding_type: "procurement",
    status: "active",
    open_date: "2026-03-01",
    close_date: "2026-06-01",
    min_award: 1000000,
    max_award: 10000000,
    eligibility: ["for_profit", "nonprofit", "research_org"],
    categories: ["climate", "energy", "environment", "international"],
    keywords: ["climate", "green energy", "resilience", "international", "environment"],
    geography: ["International", "Global"],
    url: "https://projects.worldbank.org/wb_002",
  },

  // ── TED EU (2) ────────────────────────────────────────────────────────────
  {
    id: "ted_001",
    source: "ted_eu",
    source_raw: "TED EU",
    title: "EU Public Sector Data Analytics and Civic Technology Services",
    description: "Open tender for data analytics platforms and civic technology services for EU public institutions. Small and medium enterprises encouraged to apply.",
    agency: "European Commission – DG DIGIT",
    funding_type: "procurement",
    status: "active",
    open_date: "2026-02-10",
    close_date: "2026-05-10",
    min_award: 200000,
    max_award: 2000000,
    eligibility: ["small_business", "for_profit", "nonprofit"],
    categories: ["government technology", "data analytics", "procurement", "civic tech"],
    keywords: ["civic tech", "data analytics", "government", "EU", "procurement", "SaaS"],
    geography: ["European Union", "International"],
    url: "https://ted.europa.eu/notice/-/detail/ted_001",
  },
  {
    id: "ted_002",
    source: "ted_eu",
    source_raw: "TED EU",
    title: "EU Youth Employment and Workforce Development Framework",
    description: "EU procurement for workforce development programs targeting youth unemployment, skills training, and green economy career preparation across member states.",
    agency: "European Commission – DG EMPL",
    funding_type: "grant",
    status: "active",
    open_date: "2026-03-15",
    close_date: "2026-06-15",
    min_award: 300000,
    max_award: 1500000,
    eligibility: ["nonprofit", "educational_institution", "for_profit"],
    categories: ["workforce development", "youth", "employment", "climate"],
    keywords: ["workforce", "youth", "employment", "climate", "EU", "STEM"],
    geography: ["European Union", "International"],
    url: "https://ted.europa.eu/notice/-/detail/ted_002",
  },
];

// ─── Mock Opportunities: Excluded Sources (6) ────────────────────────────────
// These should NEVER appear in V1 match results

export const MOCK_OPPORTUNITIES_EXCLUDED: NormalizedOpportunity[] = [
  {
    id: "usa_001",
    source: "usaspending",
    source_raw: "USASpending",
    title: "HISTORICAL: NIH Grant Award to Johns Hopkins – Maternal Health Research",
    description: "Historical award record from USASpending. Awarded in FY2023. Not an active opportunity.",
    agency: "National Institutes of Health",
    funding_type: "grant",
    status: "archived",
    open_date: "2023-01-01",
    close_date: "2023-03-01",
    min_award: 500000,
    max_award: 500000,
    eligibility: [],
    categories: ["maternal health", "research"],
    keywords: ["maternal health", "research", "historical"],
    geography: ["United States"],
    url: "https://www.usaspending.gov/award/usa_001",
  },
  {
    id: "usa_002",
    source: "usaspending",
    source_raw: "USASpending",
    title: "HISTORICAL: DOE Clean Energy Award – Solar Technology Institute",
    description: "Historical award record. This was a completed grant, not a live opportunity.",
    agency: "Department of Energy",
    funding_type: "grant",
    status: "archived",
    open_date: "2022-06-01",
    close_date: "2022-09-01",
    min_award: 750000,
    max_award: 750000,
    eligibility: [],
    categories: ["clean energy", "research"],
    keywords: ["clean energy", "solar", "historical"],
    geography: ["United States"],
    url: "https://www.usaspending.gov/award/usa_002",
  },
  {
    id: "nih_001",
    source: "nih_reporter",
    source_raw: "NIH RePORTER",
    title: "INTELLIGENCE: R01 – Community Interventions for Maternal Mortality Reduction",
    description: "NIH RePORTER intelligence record. Active research project being tracked for grant intelligence, not available for application.",
    agency: "National Institute on Minority Health and Health Disparities",
    funding_type: "grant",
    status: "archived",
    open_date: "2024-09-01",
    close_date: "2024-06-30",
    min_award: 400000,
    max_award: 400000,
    eligibility: [],
    categories: ["maternal health", "research", "community health"],
    keywords: ["maternal health", "community", "NIH", "intelligence"],
    geography: ["United States"],
    url: "https://reporter.nih.gov/search/nih_001",
  },
  {
    id: "nih_002",
    source: "nih_reporter",
    source_raw: "NIH RePORTER",
    title: "INTELLIGENCE: R21 – STEM Workforce Pipeline for Climate Careers",
    description: "Research intelligence record from NIH RePORTER. Used for competitive landscape analysis only.",
    agency: "National Cancer Institute",
    funding_type: "grant",
    status: "archived",
    open_date: "2024-01-01",
    close_date: "2024-12-31",
    min_award: 200000,
    max_award: 200000,
    eligibility: [],
    categories: ["STEM", "workforce", "research"],
    keywords: ["STEM", "workforce", "research", "intelligence"],
    geography: ["United States"],
    url: "https://reporter.nih.gov/search/nih_002",
  },
  {
    id: "nsf_001",
    source: "nsf_awards",
    source_raw: "NSF Awards",
    title: "INTELLIGENCE: NSF Award – Civic Technology Infrastructure Research",
    description: "Historical NSF award record. Used for grant intelligence and competitive analysis. Not available for application.",
    agency: "National Science Foundation",
    funding_type: "grant",
    status: "archived",
    open_date: "2023-09-01",
    close_date: "2026-08-31",
    min_award: 600000,
    max_award: 600000,
    eligibility: [],
    categories: ["government technology", "data systems", "research"],
    keywords: ["civic tech", "data", "government", "NSF", "research", "intelligence"],
    geography: ["United States"],
    url: "https://www.nsf.gov/awardsearch/nsf_001",
  },
  {
    id: "nsf_002",
    source: "nsf_awards",
    source_raw: "NSF Awards",
    title: "INTELLIGENCE: NSF Award – Youth STEM Climate Education Initiative",
    description: "NSF award intelligence record. Shows funded climate/STEM programs as competitive landscape data.",
    agency: "National Science Foundation",
    funding_type: "grant",
    status: "archived",
    open_date: "2023-06-01",
    close_date: "2026-05-31",
    min_award: 450000,
    max_award: 450000,
    eligibility: [],
    categories: ["climate", "STEM", "youth", "education"],
    keywords: ["youth", "STEM", "climate", "NSF", "intelligence"],
    geography: ["United States"],
    url: "https://www.nsf.gov/awardsearch/nsf_002",
  },
];

// Combined pool (all records)
export const ALL_MOCK_OPPORTUNITIES: NormalizedOpportunity[] = [
  ...MOCK_OPPORTUNITIES_ACTIVE,
  ...MOCK_OPPORTUNITIES_EXCLUDED,
];
